# SPDX-License-Identifier: CC-BY-4.0
# Copyright (C) 2023 Wavecon GmbH

[build]
  base = "docs/"
  publish = "public"
  command = "make build"

[build.environment]
  HUGO_VERSION = "0.135.0"
  NODE_VERSION = "20"
  GO_VERSION = "1.20"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "make build-preview"
